package org.schlimm.java9.jep200;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 * <a href="https://openjdk.java.net/jeps/200">JEP 200: The Modular JDK</a> <br>
 * <a href=
 * "https://bugs.openjdk.java.net/secure/attachment/72527/module-summary.html">API Description</a> <br>
 * This JEP is asking for a modular JDK, so that JDK is a set of modules. The
 * list of available modules is generated by {@link Jep200_TheModulerJdk} class.
 */
public class Jep200_TheModulerJdk {

    public static void main(String[] args) throws NoSuchFieldException, IllegalAccessException, IOException {

        Process process = Runtime.getRuntime().exec("java --list-modules");
        BufferedReader output = new BufferedReader(new InputStreamReader(process.getInputStream()));
        BufferedReader error = new BufferedReader(new InputStreamReader(process.getErrorStream()));
        System.out.println("Available Standard JDK modules:");
        output.lines().forEach(l -> System.out.println(l));
        error.lines().forEach(l -> System.out.println(l));

    }
}
